const char* songNamesJP[] = {
	"Earth Wind",
	"LA-MULANA",
	"Mr.Explorer",
	"Xelpud",
	"BONGA WANGA",
	"Fearless challenger -long version-",
	"Fearless challenger",
	"Requiem",
	"King Konda",
	"Fanfale",
	"Grand History",
	"G•I•L•D",
	"Primitive Dance",
	"Giant's Rage",
	"Curse of IRON PIPE",
	"Dodge",
	"Inferno",
	"Dangerous Raid",
	"Sacred Tomb",
	"Wise Men",
	"M.U.",
	"High-Speed Beast",
	"Grand Ritual",
	"Legendary Small Beauty",
	"Mother will be awakened",
	"Wonder of the Wonder",
	"Giant's Cry",
	"Sabbat",
	"Moon Light Dance",
	"GIGA-MAGMA",
	"In the bottom",
	"Sky Tower",
	"Fairy",
	"Song of Curry",
	"Ancient Machine",
	"Death Game",
	"Interstice of the Dimension",
	"Awaking",
	"Last Battle?",
	"Good Night Mom",
	"Escape!!!",
	"Run toward the sun",
	"GAME OVER",
	"行進曲「威風堂々」 -空中戦のテーマ-",
	"アイネ・クライネ・ナハトムジーク -573星のテーマ-",
	"舞踏組曲「ガイーヌ」より「剣の舞」 -瞑想のパオラ-",
	"この胸のむきむき",
	"歯が痛い告白",
	"伝説の樹の下でタイマン",
	"ガリウスの迷宮 -CASTLE-",
	"ガリウスの迷宮 -ワールドスタート-",
	"ガリウスの迷宮 -WORLD-",
	"ガリウスの迷宮 -神様-",
	"ガリウスの迷宮 -大悪魔の部屋-",
	"ガリウスの迷宮 -大悪魔音頭-",
	"ガリウスの迷宮 -ワールドクリア-",
	"真夜中のジャングル",
	"Treasure sealed off",
	"[没] Curse of Iron Pipe (Ver. A)",
	"[没] Aqua Wish",
	"[没] Wonder of the Wonder -Prot Type-",
	"[没] Spirit of Giants",
	"[没] Crazy Moon",
	"[没] Road of Destiny",
	"[没] ELECTRIC PROPHET",
	"[没] Mother",
	"[没] Easter",
	"[没] Sabbat -Prot Type-",
	"[没] Take me to the sky,my children",
	"[没] Good Morning Mom",
	"[没] Blood And Beast",
	"[没] Ancient Voice",
	"[没] カレーには月桂樹の葉を入れて煮込め",
	"[没] Fearless challenger 体験版",
	"[没] 行進曲「威風堂々」-空中戦のテーマ-",
	"[没] 交響曲「新世界」-５７３星のテーマ-"
};

const char* songNamesEN[] = {
	"Mr.Explorer",
	"Fearless challenger",
	"Grand History",
	"Curse of IRON PIPE",
	"Sacred Tomb",
	"Inferno",
	"M.U.",
	"Grand Ritual",
	"Primitive Dance",
	"Mother will be awakened",
	"Awaking",
	"Wonder of the Wonder",
	"Giant's Cry",
	"Sky Tower",
	"Moon Light Dance",
	"GIGA-MAGMA",
	"Song of Curry",
	"LA-MULANA",
	"Earth Wind",
	"GAME OVER",
	"Requiem",
	"Death Game",
	"Fanfare",
	"King Konda",
	"Giant's Rage",
	"High-Speed Beast",
	"Dangerous Raid",
	"In the bottom",
	"Ancient Machine",
	"Sabbat",
	"Interstice of the Dimension",
	"Last Battle?",
	"BONGA WANGA",
	"Xelpud",
	"G-U-I-L-D",
	"Wise Men",
	"Dodge",
	"Fairy",
	"Legendary Small Beauty",
	"Fearless challenger -long version-",
	"Good Night Mom",
	"Escape!!!",
	"Run toward the sun",
	"March \"Pomp And Circumstance\" ~Air Battle Theme~",
	"Eine Kleine Nachtmusik ~573 Star Theme~",
	"Dancing Musical \"Sabre Dance\" From \"Gayane\" ~Meditating Paola~",
	"This Heart Is Suitable",
	"Confession Of A Painful Tooth",
	"One-on-one Battle beneath the Legendary Tree",
	"The Maze of Galious - CASTLE -",
	"The Maze of Galious - WORLD-",
	"The Maze of Galious - God -",
	"The Maze of Galious - Great devil's room -",
	"The Maze of Galious - Great Devil Head -",
	"The Maze of Galious - World Clear -",
	"Treasure sealed off",
	"The Maze of Galious - World Start -",
	"Midnight Jungle",
	"[Unused] Mother",
	"[Unused] Easter",
	"[Unused] Wonder of the Wonder -Prot Type-",
	"[Unused] Spirit of Giants",
	"[Unused] Crazy Moon",
	"[Unused] Road of Destiny",
	"[Unused] ELECTRIC PROPHET",
	"[Unused] Sabbat -Prot Type-",
	"[Unused] Take me to the sky,my children",
	"[Unused] Good Morning Mom",
	"[Unused] Blood And Beast",
	"[Unused] Ancient Voice",
	"[Unused] Put the laurel leaves in the curry and simmer",
	"[Unused] Fearless challenger trial version",
	"[Unused] March March 'Dignity' - Theme of the Air Fight -",
	"[Unused] Symphony \"New World\" -573 Star Theme -",
	"[Unused] Curse of Iron Pipe (Ver. A)",
	"[Unused] Aqua Wish"
};

const int jukeboxOrder[] = {18, 17, 0, 33, 32, 39, 1, 20, 23, 22, 2, 34, 8, 24, 3, 36, 5, 26, 4, 35, 6, 25, 7, 38, 9, 11, 12, 29, 14, 15, 27, 13, 37, 16, 28, 21, 30, 10, 31, 40, 41, 42, 19, 43, 44, 45, 46, 47, 48, 49, 56, 50, 51, 52, 53, 54, 57, 55, 74, 75, 60, 61, 62, 63, 64, 58, 59, 65, 66, 67, 68, 69, 70, 71, 72, 73};